### ISSUE TITLE
树莓派无法运行

### ISSUE THREAD

**Issue by yanyumihuang** [Dreamacro/clash-tracing#11]
这个是不是不支持arm64![]
![报错](https://user-images.githubusercontent.com/26965886/121617570-d9548700-ca97-11eb-868c-ccb030751fcc.png)

**Comment by Dreamacro** [comment]
把 1.8-alpine 改成 1.8, influxdb 的官方 alpine 镜像不包含 arm64 v8 的镜像

**Comment by yanyumihuang** [comment]
@Dreamacro  ok了，谢谢
