### ISSUE TITLE
无法连接influxdb数据库

### ISSUE THREAD

**Issue by ycg31** [Dreamacro/clash-tracing#14]
2021/12/12 17:12:25 influxdb2client E! Write error: Post "http://influxdb:8086/api/v2/write?bucket=events&org=clash&precision=ns": dial tcp 172.21.0.2:8086: connect: connection refused

在scraper的容器里ping 172.21.0.2是可以ping通的，grafana网页也可以连上数据库
不知道scraper容器中配置文件在哪里，我看看配置文件用户密码是不是对的，从这个构造的url来看，数据库名字是对的。
另外会不会是influxdb数据库权限的问题
望大佬不吝赐教，实在是网页都翻了半天了，找不到解决办法

**Comment by fedstryale** [comment]
same here!
以前是正常的，今天升级git以后就连不上数据库了，删除后重新git也不行，应该是最新版本scraper的问题

**Comment by Dreamacro** [comment]
我这没有任何问题

**Comment by rheatin** [comment]
这个我今天也遇到了，实际上应该是没有任何影响的，如果用的openwrt的openclash的话，我发现profile的tracing没有设置，设置成true，grafana就有图表了（ws调试了半天
