### ISSUE TITLE
构建scraper失败的问题

### ISSUE THREAD

**Issue by Sagittarius** [Dreamacro/clash-tracing#17]
设置了代理，docker也无法build，这是为啥
```
Building scraper
Step 1/12 : FROM golang:alpine as builder
 ---> e8fc0c5ad389
Step 2/12 : RUN cat /etc/apk/repositories
 ---> Using cache
 ---> 18766c39a777
Step 3/12 : RUN export HTTP_PROXY=http://192.168.50.62:7890
 ---> Running in bb5f19163993
Removing intermediate container bb5f19163993
 ---> 62a8b3d9b4ba
Step 4/12 : RUN export HTTPS_PROXY=http://192.168.50.62:7890
 ---> Running in 72d6266bc64c
Removing intermediate container 72d6266bc64c
 ---> c36286cd406f
Step 5/12 : RUN apk add --no-cache make git
 ---> Running in 0a5f2373554e
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
ERROR: unable to select packages:
  git (no such package):
    required by: world[git]
  make (no such package):
    required by: world[make]
ERROR: Service 'scraper' failed to build: The command '/bin/sh -c apk add --no-cache make git' returned a non-zero code: 2
```

**Comment by Dreamacro** [comment]
直接给 alpine 换源更简单 `sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories`

**Comment by Sagittarius** [comment]
> 直接给 alpine 换源更简单 `sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories`

奇怪就奇怪在这儿，我换了也是一样，单独拎出来做curl倒是正常：
```
root@vincent-truenas[~/vincent/clash/clash-tracing]# docker-compose up -d    
Building scraper
Step 1/11 : FROM golang:alpine as builder
 ---> e8fc0c5ad389
Step 2/11 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
 ---> Running in 7f1f70a0ad8f
Removing intermediate container 7f1f70a0ad8f
 ---> dc0b2071a165
Step 3/11 : RUN apk update
 ---> Running in 609df05f35be
fetch https://mirrors.ustc.edu.cn/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
ERROR: https://mirrors.ustc.edu.cn/alpine/v3.15/main: temporary error (try again later)
WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.15/main: No such file or directory
fetch https://mirrors.ustc.edu.cn/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
ERROR: https://mirrors.ustc.edu.cn/alpine/v3.15/community: temporary error (try again later)
WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.15/community: No such file or directory
2 errors; 15 distinct packages available
ERROR: Service 'scraper' failed to build: The command '/bin/sh -c apk update' returned a non-zero code: 2
```

**Comment by Sagittarius** [comment]
> > 直接给 alpine 换源更简单 `sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories`
> 
> 奇怪就奇怪在这儿，我换了也是一样，单独拎出来做curl倒是正常：
> 
> ```
> root@vincent-truenas[~/vincent/clash/clash-tracing]# docker-compose up -d    
> Building scraper
> Step 1/11 : FROM golang:alpine as builder
>  ---> e8fc0c5ad389
> Step 2/11 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
>  ---> Running in 7f1f70a0ad8f
> Removing intermediate container 7f1f70a0ad8f
>  ---> dc0b2071a165
> Step 3/11 : RUN apk update
>  ---> Running in 609df05f35be
> fetch https://mirrors.ustc.edu.cn/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
> ERROR: https://mirrors.ustc.edu.cn/alpine/v3.15/main: temporary error (try again later)
> WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.15/main: No such file or directory
> fetch https://mirrors.ustc.edu.cn/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
> ERROR: https://mirrors.ustc.edu.cn/alpine/v3.15/community: temporary error (try again later)
> WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.15/community: No such file or directory
> 2 errors; 15 distinct packages available
> ERROR: Service 'scraper' failed to build: The command '/bin/sh -c apk update' returned a non-zero code: 2
> ```

然而我放在windows下执行了一下试试，居然就可以。
我在我的TrueNAS上就不行。 我在上面都配置好了tun的

**Comment by Sagittarius** [comment]
我在dockerfile里添加了一项 `RUN ifconfig -a`，看起来是构建的时候没有可以出网的网卡。仍然不知道啥原因

**Comment by Sagittarius** [comment]
原因已找到。因为在build镜像的过程中无法联网，可以通过指定`network`为`host`，这个跟`network_mode`的`host`并不一样，并且只在`docker-compose`的2.2或者3.4支持。详情可以参照[docker build以及docker run时使用host网络的方法](https://www.debugself.com/2018/01/17/docker_network/)和[Compose file version 3 reference
](https://docs.docker.com/compose/compose-file/compose-file-v3/#network)
