### ISSUE TITLE
tun模式下域名访问,慢dial,局域网访问图表没数据

### ISSUE THREAD

**Issue by xmapst** [Dreamacro/clash-tracing#21]
tun模式下域名访问,慢dial,局域网访问图表没数据
![image](https://user-images.githubusercontent.com/36829716/163708991-03be7e4a-ec3b-4b41-8426-5b0fb64168c5.png)

**Comment by YkeLit** [comment]
> tun模式下域名访问,慢dial,局域网访问图表没数据 ![image](https://user-images.githubusercontent.com/36829716/163708991-03be7e4a-ec3b-4b41-8426-5b0fb64168c5.png)
你好，我也遇到一样的问题，请问你怎么解决的呀

**Comment by xmapst** [comment]
> > tun模式下域名访问,慢dial,局域网访问图表没数据 ![image](https://user-images.githubusercontent.com/36829716/163708991-03be7e4a-ec3b-4b41-8426-5b0fb64168c5.png)
> > @xmapst 你好，我也遇到一样的问题，请问你怎么解决的呀

不用clash了
