### ISSUE TITLE
踩坑记录

### ISSUE THREAD

**Issue by wuzhefang** [Dreamacro/clash-tracing#24]
1. 要使用 clash premium,因为只有premium才有trace接口
2. 要在config.yaml中加入配置以开启trace功能
```
      profile:
            tracing: true
```
3. grafana的数据源要配置，在setting里。loki地址填写 http://loki:3100

**Comment by xx10n31y** [comment]
配置都是默认, 地址填写 http://loki:3100, 不行

![image](https://user-images.githubusercontent.com/57975788/168420171-515e82dd-8557-4dc5-82e5-1e0f939a470e.png)

![image](https://user-images.githubusercontent.com/57975788/168420189-42884d44-04c0-4a45-b750-cabaf336ec89.png)

**Comment by jeagerisme** [comment]
> 配置都是默认 也开启了tracing, 地址填写 http://loki:3100, 不行
> 
> ![image](https://user-images.githubusercontent.com/57975788/168420171-515e82dd-8557-4dc5-82e5-1e0f939a470e.png)
> 
> ![image](https://user-images.githubusercontent.com/57975788/168420189-42884d44-04c0-4a45-b750-cabaf336ec89.png)

可以参考下我的踩坑记录：
https://jeagerisme.blogspot.com/2022/05/clash-clash-tracing.html

**Comment by xx10n31y** [comment]
> > 配置都是默认 也开启了tracing, 地址填写 http://loki:3100, 不行
> > ![image](https://user-images.githubusercontent.com/57975788/168420171-515e82dd-8557-4dc5-82e5-1e0f939a470e.png)
> > ![image](https://user-images.githubusercontent.com/57975788/168420189-42884d44-04c0-4a45-b750-cabaf336ec89.png)
> 
> 可以参考下我的踩坑记录： https://jeagerisme.blogspot.com/2022/05/clash-clash-tracing.html

![image](https://user-images.githubusercontent.com/57975788/171088661-cc40c62d-8931-4d26-ab1c-fbf27c4243eb.png)

参照您的文章进行操作后, 依然是 `cannot connect to loki. 502` 这个错误

**Comment by xx10n31y** [comment]
> @xx10n31y 你贴下loki的容器日志呢？
> 
> $ docker logs loki

已经找到问题所在了. 因为国内环境的特殊性, 我在 `$HOME/.docker/docker.confg` 增加了以下内容导致的,  删除并重启docker之后就可以了, 感谢 
```json
{
        "proxies": {
                "default": {
                        "httpProxy": "http://172.17.0.1:7890",
                        "httpsProxy": "http://172.17.0.1:7890"
                }
        }
}
```
