### ISSUE TITLE
请教在meta内核模式下无法正常显示

### ISSUE THREAD

**Issue by TsirTV** [Dreamacro/clash-tracing#31]
TUN内核下显示正常，日志数据可以显示，切换到meta内核，日志数据可以获取，但是grafana无法显示数据，请教我需要调整哪里可以呈现？
环境
OpenWrt R22.1.1
Tun版本 2022.06.19
Mate版本alpha-g30a0834
openclashUI版本v0.45.33-beta

旁路有模式

**Comment by TsirTV** [comment]
更正：meta模式下无法获取日志信息。
profile:
  # open tracing exporter API
  tracing: true
在配置文件中也打开了

**Comment by Dreamacro** [comment]
找 meta 自行解决吧
