### ISSUE TITLE
可以有树莓派arm64的镜像吗

### ISSUE THREAD

**Issue by ifuner** [Dreamacro/clash-tracing#33]
按步骤来的，然后抛出错误了
<img width="520" alt="image" src="https://user-images.githubusercontent.com/25742540/195972682-aa0404fe-a062-42f4-bb7e-e4ce109ce0aa.png">

**Comment by Dreamacro** [comment]
目前依赖于 websocat 这个 image，这个 image 目前不支持 arm64

**Comment by ifuner** [comment]
> 目前依赖于 websocat 这个 image，这个 image 目前不支持 arm64

**Comment by sususu98** [comment]
> 按步骤来的，然后抛出错误了 <img alt="image" width="520" src="https://user-images.githubusercontent.com/25742540/195972682-aa0404fe-a062-42f4-bb7e-e4ce109ce0aa.png">

我push了一个支持arm64的镜像，将websocat的image替换为`sususu98/websocat:aarch64`即可
