### ISSUE TITLE
Grafana 高版本无法显示

### ISSUE THREAD

**Issue by fuergaosi233** [Dreamacro/clash-tracing#36]
grafana: v9.0.4 版本 前三个图表无法正常显示
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/22197568/210749440-8fe31a16-e30c-4b3c-8294-6941c7bbbd94.png">

**Comment by Michael2008S** [comment]
感觉和你的issue一样，获取的数据json格式出错导致

**Comment by Dreamacro** [comment]
fixed on 0db6bfe
