### ISSUE TITLE
多了一个错误json格式的容器ip？

### ISSUE THREAD

**Issue by Michael2008S** [Dreamacro/clash-tracing#38]
```
could not write JSON response: err while creating labelset for {="172.20.0.4", address="116.211.189.205:80", duration="18278", host="116.211.189.205", id="64f1df07-d9ca-4ddb-a6a5-be100694de11", port="45926", proxy="DIRECT", type="proxydial", type_extracted="proxydial"}: 1:2: parse error: unexpected "=" in label set, expected identifier or "}"
```

![image](https://user-images.githubusercontent.com/1240769/211871374-bd7728d2-f3c6-4025-98c5-a5bf3824986f.png)

补充查询的数据结果：（为什么每条数据前面都有 {"":"172.20.0.5"}，怎么去除这个key,val？）

![image](https://user-images.githubusercontent.com/1240769/212074456-ae70d2ab-b925-4b27-b38a-65dcca16a201.png)

**Comment by Dreamacro** [comment]
fixed on 0db6bfe
