### ISSUE TITLE
小白提问：这个东西是不是要自己写筛选器之类的东西才有用

### ISSUE THREAD

**Issue by GongT** [Dreamacro/clash-tracing#46]
如题（

配置似乎没问题（看到了一些clash输出的日志）

![image](https://github.com/Dreamacro/clash-tracing/assets/2265048/3d1bc8bd-9569-4b7b-9ba1-f9c9d4d57ddb)

**Comment by Dreamacro** [comment]
HOME -> Dashboard

**Comment by GongT** [comment]
原来在这里，找了半天没找到orz

感谢大佬
