### ISSUE TITLE
没有数据显示，怎么tracking啊

### ISSUE THREAD

**Issue by trott90** [Dreamacro/clash-tracing#7]
container起来了，里面的设置应该没问题，直接用192.168.2.250:9090/traffic可以看的到有数据，没有看到任何log，所以不知道哪里有问题

**Comment by sddpljx** [comment]
配置文件中是否添加了下面的代码呢？
```
profile:
  # open tracing exporter API
  tracing: true
```

**Comment by trott90** [comment]
解决了，我装在clash的vm gateway上，但db在host的docker上，似乎gateway里的iptable干扰了

**Comment by JokerQyou** [comment]
> 配置文件中是否添加了下面的代码呢？
> 
> ```
> profile:
>   # open tracing exporter API
>   tracing: true
> ```

This should be in the README, or somewhere in the wiki of Clash.
