### ISSUE TITLE
Unable to build scraper?

### ISSUE THREAD

**Issue by BreezyMain** [Dreamacro/clash-tracing#8]
I'm following the tutorials on the Gitbook of the clash, and trying to use clash tracing, but I meet some difficults.
Gitbook: https://lancellc.gitbook.io/clash/start-clash/using-clash-tracing#step-3-change-and-start

There is a log of the last step:
```
Building scraper
Sending build context to Docker daemon  357.4kB

Step 1/9 : FROM golang:alpine as builder
 ---> 14ee78639386
Step 2/9 : RUN apk add --no-cache make git
 ---> Using cache
 ---> fa4254405d02
Step 3/9 : WORKDIR /scraper-src
 ---> Using cache
 ---> 1fe9a29bbea1
Step 4/9 : COPY . /scraper-src
 ---> 088c6b5a4f56
Step 5/9 : RUN go mod download &&     go build -o scraper . &&     mv ./scraper /scraper
 ---> Running in 2d1c7b759fd5
go: github.com/gorilla/websocket@v1.4.2: Get "https://proxy.golang.org/github.com/gorilla/websocket/@v/v1.4.2.mod": dial tcp 216.58.200.241:443: i/o timeout
The command '/bin/sh -c go mod download &&     go build -o scraper . &&     mv ./scraper /scraper' returned a non-zero code: 1
ERROR: Service 'scraper' failed to build
```

I am sorry for trouble you to help me with this problem, because in exactly I dont know any thing about docker.
Although I have installed docker and other dependencies, I failed at the last step.
Can anybody give some advise for me? thank you!

简单来说就是照着教程来卡最后一步了，挂了半天也没搞好，求解。

**Comment by Dreamacro** [comment]
`dial tcp 216.58.200.241:443: i/o timeout` 网络问题

**Comment by BreezyMain** [comment]
> `dial tcp 216.58.200.241:443: i/o timeout` means you have network problems.

I know. But although I have used proxy for docker, it still can't pass.
I read https://docs.docker.com/network/proxy/ to have a proxy for my docker, is it wrong?

**Comment by Dreamacro** [comment]
maybe you can modify Dockerfile with https://goproxy.cn/

**Comment by ycg31** [comment]
在第6行前面加上` ENV GOPROXY https://goproxy.cn`
